export const dataKecepatanAngin = [
  {
    tanggal: "26-09-2023",
    kecepatan: 15,
    arahTerbanyak: "Utara",
    kecepatanTerbesar: 22,
    arah: "Utara",
  },
  {
    tanggal: "25-09-2023",
    kecepatan: 10,
    arahTerbanyak: "Timur Laut",
    kecepatanTerbesar: 18,
    arah: "Timur Laut",
  },
  {
    tanggal: "24-09-2023",
    kecepatan: 12,
    arahTerbanyak: "Barat Daya",
    kecepatanTerbesar: 20,
    arah: "Barat Daya",
  },
  {
    tanggal: "23-09-2023",
    kecepatan: 14,
    arahTerbanyak: "Selatan",
    kecepatanTerbesar: 19,
    arah: "Selatan",
  },
  {
    tanggal: "22-09-2023",
    kecepatan: 16,
    arahTerbanyak: "Barat Laut",
    kecepatanTerbesar: 24,
    arah: "Barat Laut",
  },
  {
    tanggal: "26-09-2023",
    kecepatan: 15,
    arahTerbanyak: "Utara",
    kecepatanTerbesar: 22,
    arah: "Utara",
  },
  {
    tanggal: "25-09-2023",
    kecepatan: 10,
    arahTerbanyak: "Timur Laut",
    kecepatanTerbesar: 18,
    arah: "Timur Laut",
  },
  {
    tanggal: "24-09-2023",
    kecepatan: 12,
    arahTerbanyak: "Barat Daya",
    kecepatanTerbesar: 20,
    arah: "Barat Daya",
  },
  {
    tanggal: "23-09-2023",
    kecepatan: 14,
    arahTerbanyak: "Selatan",
    kecepatanTerbesar: 19,
    arah: "Selatan",
  },
  {
    tanggal: "22-09-2023",
    kecepatan: 16,
    arahTerbanyak: "Barat Laut",
    kecepatanTerbesar: 24,
    arah: "Barat Laut",
  },
];
